### ISSUE TITLE
连接nginx-push-stream-module做的websocket服务时几秒后出1005问题

### ISSUE THREAD

**Issue by 1371030** [Rabtman/WsManager#1]
调试时出I/System.out: CLOSE: 1005 就退出监听了，请教下，okhttp3.5的websocket的oPong函数是删了吗？

初学者，请勿介意

**Comment by Rabtman** [comment]
收到的关闭帧没有包含状态码，那么就认为其状态码是 1005。可能是服务端哪个地方在几秒后发送了关闭。okhttp3.5之后就没有了onPong的回调了

**Comment by 1371030** [comment]
同样的代码用okhttp提供的地址ws://echo.websocket.org正常工作，因为没有onpong所以不知道回应了什么，看okhttp源码，像是pong了bin内容

**Comment by MIkeeJY** [comment]
弱弱的问下 现在是okhttp Mockserver会自动挂载后台的service嘛？？ 还是需要自己手动写一个service去保证一直在后台连接？

**Comment by 1371030** [comment]
应訪是要手动service去连接，我只是简单试用，没有深入研究

**Comment by yin450561200** [comment]
compile 'com.rabtman.wsmanager:wsmanager:1.0.2' 跟“1.0.1"有何区别（如果okhttp 的包升级就不需要解释）；再问一个问题，心跳包是自动发送还是需要自己定时发送。

**Comment by yin450561200** [comment]
心跳包是自动发送还是需要自己定时发送。
