### ISSUE TITLE
建议不要在框架层强制使用UI线程来处理回调和建立连接

### ISSUE THREAD

**Issue by origin005x** [Rabtman/WsManager#5]
建议不要在框架层强制使用UI线程来处理回调和建立连接。连接建立不应该放到UI线程做；回调是否需要使用UI线程应当由上层业务层决定。

**Comment by Rabtman** [comment]
建立连接不是走的ui线程；
框架本身的设计就是用的单例，方便全局调用，并在一处统一回调，所以将其统一到UI线程上。取得回调结果后你可以按自己的意思做任意操作。
