### ISSUE TITLE
设置心跳包报错

### ISSUE THREAD

**Issue by GillX** [Rabtman/WsManager#6]
你好，设置了pingInterval，onFailure报错：Server-sent frames must not be masked.
请问这个是什么问题，要怎么处理啊？

ps:非常多谢你的开源！

**Comment by Rabtman** [comment]
我运行项目中写的demo，并没有遇见你说的问题。
你是自己实现的时候报错吗？请提供更详细的信息。

**Comment by Rabtman** [comment]
太久无回应，有问题再重新提问
