### ISSUE TITLE
支持wss

### ISSUE THREAD

**Issue by Bertkiing** [Rabtman/WsManager#9]
能不能支持一下wss的证书验证啊
要不然使用 wss,就会报：/System.err:     at android.security.net.config.NetworkSecurityTrustManager.checkServerTrusted(NetworkSecurityTrustManager.java:94)

**Comment by Rabtman** [comment]
是你的证书问题，需要自定义校验

**Comment by Rabtman** [comment]
可以参考这个：https://juejin.im/entry/58cf9034a22b9d0064374dd9
